package grunn.world;

public enum GRUNNMessageType {
	OFFERBUNDLE, COMPONENTBID, RESULTOFCOMPONENTBID, PRODUCTIONBID, RESULTOFPRODUCTIONBID, SHIPMENTBID, RESULTOFSHIPMENTBID, NEWDAY, FINISHED, UNDEFINED
}